# Generated by Django 4.2 on 2025-03-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
    ]
